KuraProject/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vote/', include('vote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from . import views

app_name = 'vote'

urlpatterns = [
    path('', views.index, name='index'),
    path('bio', views.bio, name='bio'),
    path('location/<str:id_serial_number>/', views.location, name='location'),
    path('photo/<str:id_serial_number>/', views.photo, name='photo'),
    path('confirmation/<str:id_serial_number>/', views.confirmation, name='confirmation'),
    path('success', views.success, name='success'),
    # path('dashboard', views.dashboard, name='dashboard'),
    path('dashboard', views.voter_list, name='voter_list'),
    path('voter_list', views.voter_list, name='voter_list'),
    path('create_voter', views.create_voter, name='create_voter'),
    path('county_list', views.county_list, name='county_list'),
    path('county_detail', views.county_detail, name='county_detail'),
    path('update_county/<str:county_code>/', views.update_county, name='update_county'),
    path('delete_county/<str:county_code>/', views.delete_county, name='delete_county'),
    path('ward_list', views.ward_list, name='ward_list'),
    path('ward_detail', views.ward_detail, name='ward_detail'),
    path('update_ward/<str:ward_code>/', views.update_ward, name='update_ward'),
    path('delete_ward/<str:ward_code>/', views.delete_ward, name='delete_ward'),
    path('constituency_list', views.constituency_list, name='constituency_list'),
    path('constituency_detail', views.constituency_detail, name='constituency_detail'),
    path('update_constituency/<str:constituency_code>/', views.update_constituency, name='update_constituency'),
    path('delete_constituency/<str:constituency_code>/', views.delete_constituency, name='delete_constituency'),
    path('check_details_auth', views.check_details_auth, name='check_details_auth'),
    path('update_details_auth', views.update_details_auth, name='update_details_auth'),
    path('voter_details/<str:id_serial_number>/', views.voter_details, name='voter_details'),
    path('update_details/<str:id_serial_number>/', views.update_details, name='update_details'),
    path('signup', views.signup, name='signup'),
    path('login', views.login, name='login'),
    path('admin_login', views.admin_login, name='admin_login'),
    path('user_account', views.user_account, name='user_account'),
    path('admin_account', views.admin_account, name='admin_account'),
    path('log_out', views.log_out, name='log_out'),
    path('admin_log_out', views.admin_log_out, name='admin_log_out'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('activation_failed', views.activation_failed, name='activation_failed')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/models.py
from django.contrib.auth.models import User
from django.db import models


class County(models.Model):
    county_code = models.CharField(max_length=3, primary_key=True)
    county_name = models.CharField(max_length=200)

    def __str__(self):
        return self.county_name


class Constituency(models.Model):
    constituency_code = models.CharField(max_length=8, primary_key=True)
    constituency_name = models.CharField(max_length=200)
    county_code = models.ForeignKey(County, on_delete=models.CASCADE, default="")

    def __str__(self):
        return self.constituency_name


class Ward(models.Model):
    ward_code = models.CharField(max_length=8, primary_key=True)
    ward_name = models.CharField(max_length=200)
    constituency_code = models.ForeignKey(Constituency, on_delete=models.CASCADE)

    def __str__(self):
        return self.ward_name


class Voter(models.Model):
    id_serial_number = models.CharField(max_length=10, default=None)
    email = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, default=None)
    first_name = models.CharField(max_length=200)
    middle_name = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=10)
    photo = models.ImageField(upload_to='media', default='user.svg')

    Male = 'Male'
    Female = 'Female'
    Other = 'Other'
    GENDER_CHOICES = [
        (Male, 'Male'),
        (Female, 'Female'),
        (Other, 'Other'),
    ]
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES)
    ward_code = models.ForeignKey(Ward, on_delete=models.CASCADE)

    def __str__(self):
        return self.first_name

vote/forms.py
from django import forms
from .models import Voter, County, Constituency, Ward


class VoterForm(forms.ModelForm):
    class Meta(object):
        model = Voter
        fields = '__all__'


class CountyForm(forms.ModelForm):
    class Meta(object):
        model = County
        fields = '__all__'

vote/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail, EmailMessage
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.template.loader import render_to_string
from django.utils.datastructures import MultiValueDictKeyError
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from vote.models import County, Constituency, Ward, Voter
from KuraProject import settings
from vote.tokens import generate_token


def index(request):
    if request.user.is_authenticated and request.user.is_active:
        fname = request.user.first_name
        context = {
            'fname': fname
        }
    else:
        fname = ''
        context = {
            'fname': fname
        }
    return render(request, 'vote/user/index.html', context)


def signup(request):
    if request.method == "POST":
        username = request.POST['username']
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']

        if User.objects.filter(username=username):
            messages.error(request, "Username already exists!!")
            return redirect('vote:signup')

        if User.objects.filter(email=email):
            messages.error(request, "Email already exists!!")
            return redirect('vote:signup')

        if pass1 != pass2:
            messages.error(request, "Passwords do not match")
            return redirect('vote:signup')

        if not pass1.isalnum():
            messages.error(request, "Password must contain both letters and numbers")
            return redirect('vote:signup')

        if len(pass1) < 7:
            messages.error(request, "Password must contain at least 8 characters")
            return redirect('vote:signup')

        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name = fname
        myuser.last_name = lname
        myuser.is_active = False

        myuser.save()

        messages.success(request, "Your Account has been created successfully. \n ")
        messages.success(request, "We have sent you a confirmation link to your email. \n ")
        messages.success(request, "Please click on it to activate your account. \n ")

        # Welcome Email

        subject = "Welcome to Kura Electronic Voter Registration System"
        message = "Hello " + myuser.first_name + "\n Welcome to Kura Electronic Voter Registration System| \n Thank " \
                                                 "you for visiting our website \n We have sent you a confirmation " \
                                                 "email, please confirm your email address in order to activate your " \
                                                 "account. \n\n Thank You \n Greg Atemi "
        from_email = settings.EMAIL_HOST_USER
        to_list = [
            myuser.email
        ]
        send_mail(subject, message, from_email, to_list, fail_silently=True)

        # Email Address Confirmation Email

        current_site = get_current_site(request)
        email_subject = "Confirm your email"
        message2 = render_to_string("vote/auth/email_confirmation.html", {
            'name': myuser.first_name,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(myuser.pk)),
            'token': generate_token.make_token(myuser)
        })
        email = EmailMessage(
            email_subject,
            message2,
            settings.EMAIL_HOST_USER,
            [myuser.email],
        )
        email.fail_silently = False
        email.send()

        return redirect('vote:login')

    return render(request, 'vote/auth/signup.html')


def admin_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        pass1 = request.POST['pass1']

        user = authenticate(username=username, password=pass1)

        if user is not None:
            auth_login(request, user)
            return redirect('vote:dashboard')

        else:
            messages.error(request, "Username or Password is incorrect")
            return redirect('vote:admin_login')

    return render(request, 'vote/auth/login_admin.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        pass1 = request.POST['pass1']

        user = authenticate(username=username, password=pass1)

        if user is not None:
            auth_login(request, user)
            messages.success(request, "Login Successful.")
            return redirect('vote:index')

        else:
            messages.error(request, "Username or Password is incorrect")

    return render(request, 'vote/auth/login.html')


def admin_log_out(request):
    logout(request)
    return render(request, 'vote/admin/admin_logout.html')


def log_out(request):
    logout(request)
    return render(request, 'vote/auth/logout.html')


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        myuser = User.objects.get(pk=uid)

    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        myuser = None

    if myuser is not None and generate_token.check_token(myuser, token):
        myuser.is_active = True
        myuser.save()
        return redirect('vote:login')
    else:
        return render(request, 'vote/auth/activation_failed.html')


def activation_failed(request):
    return render(request, 'vote/auth/activation_failed.html')


def dashboard(request):
    if request.user.is_authenticated and request.user.is_staff:
        total = Voter.objects.count()
        threshold = (total / 10) * 100
        fname = request.user.first_name
        lname = request.user.last_name
        context = {
            'fname': fname,
            'lname': lname,
            'total': total,
            'threshold': threshold
        }
    else:
        messages.info(request, "Admin privileges required")
        return redirect('vote:admin_login')

    return render(request, 'vote/admin/dashboard.html', context)


@login_required
def user_account(request):
    uname = request.user.username
    fname = request.user.first_name
    lname = request.user.last_name
    email = request.user.email

    context = {
        'uname': uname,
        'fname': fname,
        'lname': lname,
        'email': email
    }

    return render(request, 'vote/user/user_account.html', context)


def county_detail(request):
    if request.user.is_authenticated and request.user.is_staff:
        fname = request.user.first_name
        lname = request.user.last_name
        context = {
            'fname': fname,
            'lname': lname
        }
        if request.method == "POST":
            county_code = request.POST['county_code']
            county_name = request.POST['county_name']

            mycounty = County.objects.create(county_code=county_code, county_name=county_name)
            mycounty.county_code = county_code
            mycounty.county_name = county_name

            mycounty.save()

            messages.success(request, "County added successfully.")

            return redirect('vote:county_list')
    else:
        messages.info(request, "Login to continue")
        return redirect('vote:admin_login')

    return render(request, 'vote/admin/county_detail.html', context)


def admin_account(request):
    if request.user.is_authenticated and request.user.is_staff:
        uname = request.user.username
        fname = request.user.first_name
        lname = request.user.last_name
        email = request.user.email
        context = {
            'uname': uname,
            'fname': fname,
            'lname': lname,
            'email': email
        }
    else:
        messages.info(request, "Login to continue")
        return redirect('vote:admin_login')

    return render(request, 'vote/admin/admin_account.html', context)


def county_list(request):
    if request.user.is_authenticated and request.user.is_staff:
        county = County.objects.all()
        fname = request.user.first_name
        lname = request.user.last_name
        context = {
            'fname': fname,
            'lname': lname,
            'county': county
        }
    else:
        messages.info(request, "Login to continue")
        return redirect('vote:admin_login')

    return render(request, 'vote/admin/county_list.html', context)


def constituency_detail(request):
    if request.user.is_authenticated and request.user.is_staff:
        county = County.objects.all()
        fname = request.user.first_name
        lname = request.user.last_name
        context = {
            'county': county,
            'fname': fname,
            'lname': lname
        }
        if request.method == "POST":
            constituency_code = request.POST['constituency_code']
            constituency_name = request.POST['constituency_name']
            county_code = request.POST['county_code']

            myconstituency = Constituency.objects.create(constituency_code=constituency_code,
                                                         constituency_name=constituency_name,
                                                         county_code_id=county_code
                                                         )

            myconstituency.constituency_code = constituency_code
            myconstituency.constituency_name = constituency_name
            myconstituency.county_code_id = county_code

            myconstituency.save()

templates/vote/bio.html
{% extends 'vote/base.html' %}
{% load static %}
{% block title_block %}
    <title>Bio Data</title>
{% endblock %}

{% block body_block %}
    <div class="parent2">
        <div class="title">
            Step 1 of 4: Personal Information
        </div>
        <div class="stepper">
            <img class="icon" src="{% static 'images/current.svg' %}" alt="current">
            <div class="separator"></div>
            <img class="icon" src="{% static 'images/circle.svg' %}" alt="circle">
            <div class="separator"></div>
            <img class="icon" src="{% static 'images/circle.svg' %}" alt="circle">
            <div class="separator"></div>
            <img class="icon" src="{% static 'images/circle.svg' %}" alt="circle">
        </div>

        <div class="content">
            Kindly fill up the following fields as correctly and accurately as possible.
        </div>
        <div class="content">
            Please note that providing false information is a crime punishable by law.
        </div>
        <div class="formWrapper">
            <div class="form">
                <form action="" method="post">
                {% csrf_token %}
                    <div class="fieldWrapper">
                        {{ form.subject.errors }}
                        <label for="id_Engine_no">ID Number</label>
                        <input class="input" type="text" name="License_plate_no" maxlength="10" required="" id="id_License_plate_no">
                    </div>

                    <div class="fieldWrapper">
                        {{ form.subject.errors }}
                        <label for="id_Engine_no">First Name</label>
                        <input class="input" type="text" name="License_plate_no" maxlength="254" required="" id="id_License_plate_no">
                    </div>

                    <div class="fieldWrapper">
                        {{ form.subject.errors }}
                        <label for="id_Engine_no">Middle Name</label>
                        <input class="input" type="text" name="Engine_no" maxlength="6" required="" id="id_Engine_no">
                    </div>

                    <div class="fieldWrapper">
                        {{ form.subject.errors }}
                        <label for="id_Mileage">Surname</label>
                        <input class="input" type="text" name="surname" maxlength="254" required="" id="id_Mileage">
                    </div>

                    <div class="fieldWrapper">
                        {{ form.subject.errors }}
                        <label for="id_gender">Gender</label>
                        <select class="input" name="gender" required="" id="id_gender">
                            <option value="" selected=""></option>
                            <option value="648641">Male</option>
                            <option value="265484">Female</option>
                            <option value="265484">Other</option>
                        </select>
                    </div>

                    <div class="fieldWrapper">
                        {{ form.subject.errors }}
                        <label for="id_date_registered">Phone Number</label>
                        <input class="input" type="text" name="date_registered" required="" id="id_date_registered">
                    </div>

                    <div class="fieldWrapper">
                        {{ form.subject.errors }}
                        <label for="id_date_registered">Email Address</label>
                        <input class="input" type="text" name="date_registered" required="" id="id_date_registered">
                    </div>

                    <div class="button-group">
                        <a class="submit" href={% url 'vote:bio' %}>CLEAR</a>
                        <input id="submit2" type="submit" value="NEXT"/>
{#                        <a class="submit" href={% url 'vote:location' %}>NEXT</a>#}
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/vote/confirmation.html
{% extends 'vote/base.html' %}
{% load static %}
{% block title_block %}
    <title>Confirm and Submit</title>
{% endblock %}

{% block body_block %}
    <div class="parent2">
        <div class="title">
            Step 4 of 4: Confirmation and Submission
        </div>
        <div class="stepper">
            <img class="icon" src="{% static 'images/check.svg' %}" alt="current">
            <div class="separator"></div>
            <img class="icon" src="{% static 'images/check.svg' %}" alt="circle">
            <div class="separator"></div>
            <img class="icon" src="{% static 'images/check.svg' %}" alt="circle">
            <div class="separator"></div>
            <img class="icon" src="{% static 'images/current.svg' %}" alt="circle">
        </div>

        <div class="content">
            Kindly ensure that all details filled below are correct and accurate.
        </div>
        <div class="content">
            Please note that providing false information is a crime punishable by law.
        </div>
        <div class="formWrapper">
            <div class="form">
                <p>Personal Details</p>
                <form action="" method="post">
                {% csrf_token %}
                    <div class="fieldWrapper_group">
                        <div class="fieldWrapper2">
                            {{ form.subject.errors }}
                            <label for="id_Engine_no">ID Number</label>
                            <input class="input" type="text" name="License_plate_no" maxlength="254" required="" id="id_License_plate_no">
                        </div>

                        <div class="spacer"></div>

                        <div class="fieldWrapper2">
                            {{ form.subject.errors }}
                            <label for="id_Constituency">First Name</label>
                            <input class="input" type="text" name="License_plate_no" maxlength="254" required="" id="id_License_plate_no">
                        </div>
                    </div>

                    <div class="fieldWrapper_group">
                        <div class="fieldWrapper2">
                            {{ form.subject.errors }}
                            <label for="id_Engine_no">Middle Name</label>
                            <input class="input" type="text" name="License_plate_no" maxlength="254" required="" id="id_License_plate_no">
                        </div>

                        <div class="spacer"></div>

                        <div class="fieldWrapper2">
                            {{ form.subject.errors }}
                            <label for="id_Constituency">Last Name</label>
                            <input class="input" type="text" name="License_plate_no" maxlength="254" required="" id="id_License_plate_no">
                        </div>
                    </div>

                    <div class="fieldWrapper_group">
                        <div class="fieldWrapper2">
                            {{ form.subject.errors }}
                            <label for="id_Engine_no">Phone Number</label>
                            <input class="input" type="text" name="License_plate_no" maxlength="254" required="" id="id_License_plate_no">
                        </div>

                        <div class="spacer"></div>

                        <div class="fieldWrapper2">
                            {{ form.subject.errors }}
                            <label for="id_Constituency">Gender</label>
                            <select class="input" name="constituency" required="" id="id_Constituency">
                                <option value="" selected=""></option>
                                <option value="648641">Male</option>
                                <option value="265484">Female</option>
                                <option value="265484">Other</option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="formWrapper">
            <div class="form">
                <p>Location Details</p>
                <form action="" method="post">
                {% csrf_token %}
                    <div class="fieldWrapper_group">
                        <div class="fieldWrapper2">
                            {{ form.subject.errors }}
                            <label for="id_Engine_no">County</label>
                            <select class="input" name="constituency" required="" id="id_Constituency">
                                <option value="" selected=""></option>
                                <option value="648641">Male</option>
                                <option value="265484">Female</option>
                                <option value="265484">Other</option>
                            </select>
                        </div>

                        <div class="spacer"></div>

                        <div class="fieldWrapper2">
                            {{ form.subject.errors }}
                            <label for="id_Constituency">Constituency</label>
                            <select class="input" name="constituency" required="" id="id_Constituency">
                                <option value="" selected=""></option>
                                <option value="648641">Male</option>
                                <option value="265484">Female</option>
                                <option value="265484">Other</option>
                            </select>
                        </div>
                    </div>

                    <div class="fieldWrapper_group">
                        <div class="fieldWrapper2">
                            {{ form.subject.errors }}
                            <label for="id_Engine_no">Ward</label>
                            <select class="input" name="constituency" required="" id="id_Constituency">
                                <option value="" selected=""></option>
                                <option value="648641">Male</option>
                                <option value="265484">Female</option>
                                <option value="265484">Other</option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="formWrapper">
            <div class="form">
                <form action="" method="post">
                {% csrf_token %}
                    <div class="fieldWrapper">
                        {{ form.subject.errors }}
                        <label for="id_County">Photo</label>
                        <input type="file" class="input" accept="image/*" onchange="loadFile(event)" value="Add Photo">
                        <img id="output" src="{% static 'images/user.svg' %}"/>

                        <input type="reset" value="Remove Photo">

                    </div>

                </form>
            </div>
        </div>

        <div class="button-parent">
            <div class="button-group2">
                <a class="submit" href={% url 'vote:bio' %}>BACK</a>
                <input id="submit2" type="submit" value="SUBMIT DETAILS"/>
            </div>
        </div>

    </div>

</div>

{% endblock %}

templates/vote/location.html
{% extends 'vote/base.html' %}
{% load static %}
{% block title_block %}
    <title>Location Data</title>
{% endblock %}

{% block body_block %}
    <div class="parent2">
        <div class="title">
            Step 2 of 4: Location Data
        </div>
        <div class="stepper">
            <img class="icon" src="{% static 'images/check.svg' %}" alt="current">
            <div class="separator"></div>
            <img class="icon" src="{% static 'images/current.svg' %}" alt="circle">
            <div class="separator"></div>
            <img class="icon" src="{% static 'images/circle.svg' %}" alt="circle">
            <div class="separator"></div>
            <img class="icon" src="{% static 'images/circle.svg' %}" alt="circle">
        </div>

        <div class="content">
            Kindly fill up the following fields as correctly and accurately as possible.
        </div>
        <div class="content">
            Please note that providing false information is a crime punishable by law.
        </div>
        <div class="formWrapper">
            <div class="form">
                <form action="" method="post">
                {% csrf_token %}
                    <div class="fieldWrapper">
                        {{ form.subject.errors }}
                        <label for="id_County">County</label>
                        <select class="input" name="county" required="" id="id_County">
                            <option value="" selected=""></option>
                            <option value="648641">Nairobi</option>
                            <option value="265484">Kiambu</option>
                            <option value="265484">Kajiado</option>
                        </select>
                    </div>

                    <div class="fieldWrapper">
                        {{ form.subject.errors }}
                        <label for="id_Constituency">Constituency</label>
                        <select class="input" name="constituency" required="" id="id_Constituency">
                            <option value="" selected=""></option>
                            <option value="648641">Male</option>
                            <option value="265484">Female</option>
                            <option value="265484">Other</option>
                        </select>
                    </div>

                    <div class="fieldWrapper">
                        {{ form.subject.errors }}
                        <label for="id_ward">Ward</label>
                        <select class="input" name="ward" required="" id="id_ward">
                            <option value="" selected=""></option>
                            <option value="648641">Male</option>
                            <option value="265484">Female</option>
                            <option value="265484">Other</option>
                        </select>
                    </div>

                    <div class="button-group">
                        <a class="submit" href={% url 'vote:bio' %}>BACK</a>
                        <input id="submit2" type="submit" value="SUBMIT"/>
                        <a class="submit" href={% url 'vote:location' %}>NEXT</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/vote/success.html
{% extends 'vote/base.html' %}
{% load static %}
{% block title_block %}
    <title>Success</title>
{% endblock %}

{% block body_block %}
    <div class="parent">
        <div class="banner-container">
            <img class="banner" src="{% static 'images/Banner.svg' %}" alt="logo">
        </div>
        <div class="title">
            SUCCESS!
        </div>

        <div class="content">
            You have been successfully registered into the National Voting Roll.
        </div>
        <div class="content">
            For more details about the voting process visit https://iebc.gov.ke
        </div>
        <div class="content">
            Good luck in the election
        </div>
        <div class="button-container">
            <a class="submit2" href="/">
                BACK TO HOME SCREEN
            </a>
        </div>
    </div>

{% endblock %}