KuraProject/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vote/', include('vote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from . import views

app_name = 'vote'

urlpatterns = [
    path('', views.index, name='index'),
    path('bio', views.bio, name='bio'),
    path('location/<str:id_serial_number>/', views.location, name='location'),
    path('photo/<str:id_serial_number>/', views.photo, name='photo'),
    path('confirmation/<str:id_serial_number>/', views.confirmation, name='confirmation'),
    path('success', views.success, name='success'),
    # path('dashboard', views.dashboard, name='dashboard'),
    path('dashboard', views.voter_list, name='voter_list'),
    path('voter_list', views.voter_list, name='voter_list'),
    path('create_voter', views.create_voter, name='create_voter'),
    path('county_list', views.county_list, name='county_list'),
    path('county_detail', views.county_detail, name='county_detail'),
    path('update_county/<str:county_code>/', views.update_county, name='update_county'),
    path('delete_county/<str:county_code>/', views.delete_county, name='delete_county'),
    path('ward_list', views.ward_list, name='ward_list'),
    path('ward_detail', views.ward_detail, name='ward_detail'),
    path('update_ward/<str:ward_code>/', views.update_ward, name='update_ward'),
    path('delete_ward/<str:ward_code>/', views.delete_ward, name='delete_ward'),
    path('constituency_list', views.constituency_list, name='constituency_list'),
    path('constituency_detail', views.constituency_detail, name='constituency_detail'),
    path('update_constituency/<str:constituency_code>/', views.update_constituency, name='update_constituency'),
    path('delete_constituency/<str:constituency_code>/', views.delete_constituency, name='delete_constituency'),
    path('check_details_auth', views.check_details_auth, name='check_details_auth'),
    path('update_details_auth', views.update_details_auth, name='update_details_auth'),
    path('voter_details/<str:id_serial_number>/', views.voter_details, name='voter_details'),
    path('update_details/<str:id_serial_number>/', views.update_details, name='update_details'),
    path('signup', views.signup, name='signup'),
    path('login', views.login, name='login'),
    path('admin_login', views.admin_login, name='admin_login'),
    path('user_account', views.user_account, name='user_account'),
    path('admin_account', views.admin_account, name='admin_account'),
    path('log_out', views.log_out, name='log_out'),
    path('admin_log_out', views.admin_log_out, name='admin_log_out'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('activation_failed', views.activation_failed, name='activation_failed')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/models.py
from django.contrib.auth.models import User
from django.db import models


class County(models.Model):
    county_code = models.CharField(max_length=3, primary_key=True)
    county_name = models.CharField(max_length=200)

    def __str__(self):
        return self.county_name


class Constituency(models.Model):
    constituency_code = models.CharField(max_length=8, primary_key=True)
    constituency_name = models.CharField(max_length=200)
    county_code = models.ForeignKey(County, on_delete=models.CASCADE, default="")

    def __str__(self):
        return self.constituency_name


class Ward(models.Model):
    ward_code = models.CharField(max_length=8, primary_key=True)
    ward_name = models.CharField(max_length=200)
    constituency_code = models.ForeignKey(Constituency, on_delete=models.CASCADE)

    def __str__(self):
        return self.ward_name


class Voter(models.Model):
    id_serial_number = models.CharField(max_length=10, default=None)
    email = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, default=None)
    first_name = models.CharField(max_length=200)
    middle_name = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=10)
    photo = models.ImageField(upload_to='media', default='user.svg')

    Male = 'Male'
    Female = 'Female'
    Other = 'Other'
    GENDER_CHOICES = [
        (Male, 'Male'),
        (Female, 'Female'),
        (Other, 'Other'),
    ]
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES)
    ward_code = models.ForeignKey(Ward, on_delete=models.CASCADE)

    def __str__(self):
        return self.first_name

vote/forms.py
from django import forms
from .models import Voter, County, Constituency, Ward


class VoterForm(forms.ModelForm):
    class Meta(object):
        model = Voter
        fields = '__all__'


class CountyForm(forms.ModelForm):
    class Meta(object):
        model = County
        fields = '__all__'

vote/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail, EmailMessage
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.template.loader import render_to_string
from django.utils.datastructures import MultiValueDictKeyError
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from vote.models import County, Constituency, Ward, Voter
from KuraProject import settings
from vote.tokens import generate_token


def index(request):
    if request.user.is_authenticated and request.user.is_active:
        fname = request.user.first_name
        context = {
            'fname': fname
        }
    else:
        fname = ''
        context = {
            'fname': fname
        }
    return render(request, 'vote/user/index.html', context)


def signup(request):
    if request.method == "POST":
        username = request.POST['username']
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']

        if User.objects.filter(username=username):
            messages.error(request, "Username already exists!!")
            return redirect('vote:signup')

        if User.objects.filter(email=email):
            messages.error(request, "Email already exists!!")
            return redirect('vote:signup')

        if pass1 != pass2:
            messages.error(request, "Passwords do not match")
            return redirect('vote:signup')

        if not pass1.isalnum():
            messages.error(request, "Password must contain both letters and numbers")
            return redirect('vote:signup')

        if len(pass1) < 7:
            messages.error(request, "Password must contain at least 8 characters")
            return redirect('vote:signup')

        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name = fname
        myuser.last_name = lname
        myuser.is_active = False

        myuser.save()

        messages.success(request, "Your Account has been created successfully. \n ")
        messages.success(request, "We have sent you a confirmation link to your email. \n ")
        messages.success(request, "Please click on it to activate your account. \n ")

        # Welcome Email

        subject = "Welcome to Kura Electronic Voter Registration System"
        message = "Hello " + myuser.first_name + "\n Welcome to Kura Electronic Voter Registration System| \n Thank " \
                                                 "you for visiting our website \n We have sent you a confirmation " \
                                                 "email, please confirm your email address in order to activate your " \
                                                 "account. \n\n Thank You \n Greg Atemi "
        from_email = settings.EMAIL_HOST_USER
        to_list = [
            myuser.email
        ]
        send_mail(subject, message, from_email, to_list, fail_silently=True)

        # Email Address Confirmation Email

        current_site = get_current_site(request)
        email_subject = "Confirm your email"
        message2 = render_to_string("vote/auth/email_confirmation.html", {
            'name': myuser.first_name,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(myuser.pk)),
            'token': generate_token.make_token(myuser)
        })
        email = EmailMessage(
            email_subject,
            message2,
            settings.EMAIL_HOST_USER,
            [myuser.email],
        )
        email.fail_silently = False
        email.send()

        return redirect('vote:login')

    return render(request, 'vote/auth/signup.html')


def admin_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        pass1 = request.POST['pass1']

        user = authenticate(username=username, password=pass1)

        if user is not None:
            auth_login(request, user)
            return redirect('vote:dashboard')

        else:
            messages.error(request, "Username or Password is incorrect")
            return redirect('vote:admin_login')

    return render(request, 'vote/auth/login_admin.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        pass1 = request.POST['pass1']

        user = authenticate(username=username, password=pass1)

        if user is not None:
            auth_login(request, user)
            messages.success(request, "Login Successful.")
            return redirect('vote:index')

        else:
            messages.error(request, "Username or Password is incorrect")

    return render(request, 'vote/auth/login.html')


def admin_log_out(request):
    logout(request)
    return render(request, 'vote/admin/admin_logout.html')


def log_out(request):
    logout(request)
    return render(request, 'vote/auth/logout.html')


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        myuser = User.objects.get(pk=uid)

    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        myuser = None

    if myuser is not None and generate_token.check_token(myuser, token):
        myuser.is_active = True
        myuser.save()
        return redirect('vote:login')
    else:
        return render(request, 'vote/auth/activation_failed.html')


def activation_failed(request):
    return render(request, 'vote/auth/activation_failed.html')


def dashboard(request):
    if request.user.is_authenticated and request.user.is_staff:
        total = Voter.objects.count()
        threshold = (total / 10) * 100
        fname = request.user.first_name
        lname = request.user.last_name
        context = {
            'fname': fname,
            'lname': lname,
            'total': total,
            'threshold': threshold
        }
    else:
        messages.info(request, "Admin privileges required")
        return redirect('vote:admin_login')

    return render(request, 'vote/admin/dashboard.html', context)


@login_required
def user_account(request):
    uname = request.user.username
    fname = request.user.first_name
    lname = request.user.last_name
    email = request.user.email

    context = {
        'uname': uname,
        'fname': fname,
        'lname': lname,
        'email': email
    }

    return render(request, 'vote/user/user_account.html', context)


def county_detail(request):
    if request.user.is_authenticated and request.user.is_staff:
        fname = request.user.first_name
        lname = request.user.last_name
        context = {
            'fname': fname,
            'lname': lname
        }
        if request.method == "POST":
            county_code = request.POST['county_code']
            county_name = request.POST['county_name']

            mycounty = County.objects.create(county_code=county_code, county_name=county_name)
            mycounty.county_code = county_code
            mycounty.county_name = county_name

            mycounty.save()

            messages.success(request, "County added successfully.")

            return redirect('vote:county_list')
    else:
        messages.info(request, "Login to continue")
        return redirect('vote:admin_login')

    return render(request, 'vote/admin/county_detail.html', context)


def admin_account(request):
    if request.user.is_authenticated and request.user.is_staff:
        uname = request.user.username
        fname = request.user.first_name
        lname = request.user.last_name
        email = request.user.email
        context = {
            'uname': uname,
            'fname': fname,
            'lname': lname,
            'email': email
        }
    else:
        messages.info(request, "Login to continue")
        return redirect('vote:admin_login')

    return render(request, 'vote/admin/admin_account.html', context)


def county_list(request):
    if request.user.is_authenticated and request.user.is_staff:
        county = County.objects.all()
        fname = request.user.first_name
        lname = request.user.last_name
        context = {
            'fname': fname,
            'lname': lname,
            'county': county
        }
    else:
        messages.info(request, "Login to continue")
        return redirect('vote:admin_login')

    return render(request, 'vote/admin/county_list.html', context)


def constituency_detail(request):
    if request.user.is_authenticated and request.user.is_staff:
        county = County.objects.all()
        fname = request.user.first_name
        lname = request.user.last_name
        context = {
            'county': county,
            'fname': fname,
            'lname': lname
        }
        if request.method == "POST":
            constituency_code = request.POST['constituency_code']
            constituency_name = request.POST['constituency_name']
            county_code = request.POST['county_code']

            myconstituency = Constituency.objects.create(constituency_code=constituency_code,
                                                         constituency_name=constituency_name,
                                                         county_code_id=county_code
                                                         )

            myconstituency.constituency_code = constituency_code
            myconstituency.constituency_name = constituency_name
            myconstituency.county_code_id = county_code

            myconstituency.save()

templates/vote/user/auth.html
{% extends 'vote/user/base.html' %}
{% load static %}
{% block title_block %}
    <title>Authorization</title>
{% endblock %}

{% block body_block %}
    <div class="parent2">
        <div class="title">
            Update Registration Details
        </div>

        <div class="content2">
            <div>
                To check your registration details, please input your ID Number
            </div>
        </div>

        <div class="content2">
            <div>
                Please note that submitting false information is punishable by Kenyan law
            </div>
        </div>

        <div class="formWrapper">
            <div class="form">
                <form action="" method="post">
                {% csrf_token %}
                    <div class="fieldWrapper">
                        {{ form.subject.errors }}
                        <label for="id_Engine_no">ID Number</label>
                        <input class="input" type="text" name="License_plate_no" maxlength="10" required="" id="id_License_plate_no">
                    </div>

                    <div class="button-group">
                        <input type="reset" class="submit" value="CLEAR">
                        <input id="submit2" type="submit" value="NEXT"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
<a href={% url 'vote:auth2' %}>NEXT</a>
{% endblock %}

templates/vote/user/auth3.html
{% extends 'vote/user/base.html' %}
{% load static %}
{% block title_block %}
    <title>Authorization</title>
{% endblock %}

{% block body_block %}
    <div class="parent2">
        <div class="content2">
            <div>
                Your record does not exist in the system
            </div>
        </div>

        <div class="content2">
            <div>
                Please click the button below to visit the Homepage
            </div>
        </div>

        <div class="button-container">
            <a class="submit2" href="/">
                HOMEPAGE
            </a>
        </div>
    </div>
{% endblock %}

templates/vote/user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.png'%}">
    <link rel="stylesheet" type="text/css" href="/static/styles/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;1,400&family=Open+Sans:wght@300;400;500&display=swap" rel="stylesheet">
    {% block title_block %}
    {% endblock %}
</head>

<body>
<div class="parent">
    <div class="navbar">

        <a href="{% url 'vote:index' %}">
            <img class="brand" src="{% static 'images/logo.svg' %}" alt="logo">
        </a>
        <ul>
            <li><a href="/vote">HOME</a> </li>
            <li><a href="#">CONTACT</a> </li>
            <li>
                {% if user.is_authenticated %}
                    <div class="account">
                        <a href={% url 'vote:user_account' %}>Hi, {{ fname }} </a>
                    </div>
                {% else %}
                    <div class="account">
                        <a href={% url 'vote:login' %}>LOGIN</a>
                    </div>
                {% endif %}
            </li>
        </ul>
    </div>

    <div class="navbar_small">
        <div>
            <a href="{% url 'vote:index' %}">
                <img class="brand_small" src="{% static 'images/logo.svg' %}" alt="logo">
            </a>
        </div>
        <div>
            <a href="{% url 'vote:user_account' %}">
                <img class="burger" src="{% static 'images/user.svg' %}" alt="logo">
            </a>
        </div>
    </div>

    {% block body_block %}
    {% endblock %}

<div>

{% block footer_block %}
    <div class="footer">
        <img class="brand-footer" src="{% static 'images/logo.svg' %}" alt="logo">
        <div class="map">
            <img src="{% static 'images/map.svg' %}" alt="map">
        </div>
        <div class="content-footer">
            <div id="wrapper">
                <div id="header">Services</div>
                <ul id="content">
                    <li><a href={% url 'vote:bio' %}>Voter Registration</a></li>
                    <li><a href={% url 'vote:update_details_auth' %}>Update Registration</a></li>
                    <li><a href={% url 'vote:check_details_auth' %}>Check Registration Status</a></li>
                </ul>
            </div>

            <div id="right-bottom-wrapper">
                <div id="header">Follow Us</div>
                <div id="icons">
                    <div class="first">
                        <img alt="facebook" src="{% static 'images/youtube.svg' %}">
                    </div>
                    <div class="first">
                        <img alt="twitter" src="{% static 'images/facebook.svg' %}">
                    </div>
                    <div class="first">
                        <img alt="instagram" src="{% static 'images/instagram.svg' %}">
                    </div>
                    <div class="last">
                        <img alt="email" src="{% static 'images/twitter.svg' %}">
                    </div>
                </div>
            </div>


        </div>
        <div class="content-footer">
            <div id="wrapper">
                <div id="header">About Us</div>
                <ul id="content">
                    <li><a href="#">Our Vision</a></li>
                    <li><a href="#">Our Mission</a></li>
                    <li><a href="#">Our Leaders</a></li>
                </ul>
            </div>

            <div id="bottom-wrapper">
                <div id="header">
                    <div>
                        Our Newsletter
                    </div>
                </div>
                <form>
                    <input placeholder="johndoe@mail.com">
                    <button class="sub-btn">Subscribe</button>
                </form>
            </div>

        </div>
    </div>

    <script>
        var countyObject = {
            "Nairobi": {
                "Starehe" : ['Nairobi-Central 10000001', 'Ngara 10000002','Pangani 10000003','Kariakor 10000004','Landimawe 10000005','Nairobi-South 10000006'],
                "Dagoretti North" : ['Kilimani 10000007', 'Kawangware 10000008','Gatina 10000009','Kileleshwa 10000010','Kabiro 10000011'],
                "Dagoretti South" : ['Mutuini 10000012', 'Ngando 10000013', 'Riruta 10000014', 'Uthiru 10000015', 'Waithaka 10000016'],
                "Westlands" : ['Kitusuru 10000017', 'Parklands 10000018', 'Kangemi 10000019', 'Karura 10000020', 'Mountain-View 10000021'],
                "Langata" : ['Mugumoini 10000084', 'Karen 10000022','Nairobi-West 10000023','Nyayo-Highrise 10000024','South-C 10000025'],
                "Kibra" : ['Laini-Saba 10000026', 'Lindi 10000027','Makina 10000028','Sarangombe 10000029'],
                "Roysambu" : ['Githurai 10000030', 'Kahawa-West 10000031','Zimmerman 10000032','Roysambu 10000033','Kahawa 10000034'],
                "Kasarani" : ['Clay-City 10000035', 'Mwiki 10000036','Kasarani 10000037','Njiru 10000038','Ruai 10000039'],
                "Ruaraka" : ['Baba-Dogo 10000040', 'Utalii 10000041','Mathare-North 10000042','Lucky-Summer 10000043','Korogocho 10000085'],
                "Embakasi South" : ['Imara-Daima 10000044', 'Kwa-Njenga 10000045','Kwa-Reuben 10000046','Pipeline 10000047','Kware 10000048'],
                "Embakasi North" : ['Kariobangi-North 10000049', 'Dandora-Area-1 10000050','Dandora-Area-2 10000051','Dandora-Area-3 10000052','Dandora-Area-4 10000053'],
                "Embakasi Central" : ['Kayole-North 10000054', 'Kayole-Central 10000055','Kayole-South 10000056','Komarock 10000057','Matopeni/Spring-Valley 10000058'],
                "Embakasi East" : ['Upper-Savannah 10000059', 'Lower-Savannah 10000060','Embakasi 10000061','Utawala 10000062','Mihango 10000063'],
                "Embakasi West" : ['Umoja-1 10000064', 'Umoja-2 10000065','Mowlem 10000066','Kariobangi-South 10000067','Maringo-Hamza 10000068'],
                "Makadara" : ['Harambee 10000069', 'Viwandani 10000070','Makongeni 10000071','Pumwani 10000072','Eastleigh-North 10000073'],
                "Kamukunji" : ['Eastleigh-South 10000074', 'Airbase 10000075','Carlifonia 10000076','Ngara 10000077','Nairobi-Central 10000078'],
                "Mathare" : ['Mabatini 10000079', 'Huruma 10000080','Ngei 10000081','Mlango-Kubwa 10000082','Kiamaiko 10000083']
            }
        }
        window.onload = function () {
            var countySel = document.getElementById("county");
            var constituencySel = document.getElementById("constituency");
            var wardSel = document.getElementById("ward_code");
            for (var x in countyObject) {
                countySel.options[countySel.options.length] = new Option(x, x);
            }
            countySel.onchange = function () {
                console.log("wewe");
                constituencySel.length = 1;
                wardSel.length = 1;
                for (var y in countyObject[this.value]) {
                    constituencySel.options[constituencySel.options.length] = new Option(y, y);
                }
            }
            constituencySel.onchange = function () {
                wardSel.length = 1;
                var z = countyObject[countySel.value][this.value];
                for (var i = 0; i < z.length; i++) {
                    var name = z[i].split(" ")[0]
                    var value = z[i].split(" ")[1]
                    wardSel.options[wardSel.options.length] = new Option(name, value);

                }
            }
        }
    </script>

{% endblock %}
</body>
</html>

templates/vote/user/bio.html
{% extends 'vote/user/base.html' %}
{% load static %}
{% block title_block %}
    <title>Bio Data</title>
{% endblock %}

{% block body_block %}
    <div class="parent2">
        <div class="title">
            Step 1 of 4: Personal Information
        </div>
        <div class="stepper">
            <img class="icon" src="{% static 'images/current.svg' %}" alt="current">
            <div class="separator"></div>
            <img class="icon" src="{% static 'images/circle.svg' %}" alt="circle">
            <div class="separator"></div>
            <img class="icon" src="{% static 'images/circle.svg' %}" alt="circle">
            <div class="separator"></div>
            <img class="icon" src="{% static 'images/circle.svg' %}" alt="circle">
        </div>

        <div class="content">
            Kindly fill up the following fields as correctly and accurately as possible.
        </div>
        <div class="content">
            Please note that providing false information is a crime punishable by law.
        </div>
        <div class="formWrapper">
            <div class="form">
                <form action="" method="post">
                {% csrf_token %}
                    <div class="fieldWrapper">
                        <label for="id_serial_number">ID Serial Number</label>
                        <input class="input" type="text" name="id_serial_number" maxlength="9" id="id_serial_number" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="first_name">First Name</label>
                        <input class="input" type="text" name="first_name" maxlength="254" id="first_name" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="middle_name">Middle Name</label>
                        <input class="input" type="text" name="middle_name" maxlength="254" id="middle_name" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="surname">Surname</label>
                        <input class="input" type="text" name="surname" maxlength="254" id="surname" required>
                    </div>

                    <div class="fieldWrapper">
                        <label for="gender">Gender</label>
                        <select class="input" name="gender" id="gender" required>
                            <option value="" selected=""></option>
                            <option value="Male">Male</option>
                            <option value="Female">Female</option>
                            <option value="Other">Other</option>
                        </select>
                    </div>

                    <div class="fieldWrapper">
                        <label for="phone_number">Phone Number</label>
                        <input class="input" type="text" name="phone_number" maxlength="10" id="phone_number" required>
                    </div>

                    <div class="button-group">
                        <input type="reset" class="submit" value="CLEAR">
                        <input id="submit2" type="submit" value="NEXT"/>
                    </div>

                </form>
            </div>
        </div>
    </div>
{#<a href={% url 'vote:location' %}>NEXT</a>#}
{#<a id="button5" href="{% url 'vote:location' Voter.email %}">NEXT</a>#}
{% endblock %}

templates/vote/user/location.html
{% extends 'vote/user/base.html' %}
{% load static %}
{% block title_block %}
    <title>Location Data</title>
{% endblock %}

{% block body_block %}
    <div class="parent2">
        <div class="title">
            Step 2 of 4: Location Data
        </div>
        <div class="stepper">
            <img class="icon" src="{% static 'images/check.svg' %}" alt="current">
            <div class="separator"></div>
            <img class="icon" src="{% static 'images/current.svg' %}" alt="circle">
            <div class="separator"></div>
            <img class="icon" src="{% static 'images/circle.svg' %}" alt="circle">
            <div class="separator"></div>
            <img class="icon" src="{% static 'images/circle.svg' %}" alt="circle">
        </div>

        <div class="content">
            Kindly fill up the following fields as correctly and accurately as possible.
        </div>
        <div class="content">
            Please note that providing false information is a crime punishable by law.
        </div>

        <div class="formWrapper">
            <div class="form">
                <form action="" method="post">
                {% csrf_token %}
                    <div class="fieldWrapper">
                        <label for="county">County</label>
                        <select class="input" name="county" id="county" required>
                            <option value="" selected="selected">Select County</option>
                        </select>
                    </div>

                    <div class="fieldWrapper">
                        <label for="constituency">Constituency</label>
                        <select class="input" name="constituency" id="constituency" required="">
                            <option value="" selected="selected"> Select County first</option>
                        </select>
                    </div>

                    <div class="fieldWrapper">
                        <label for="ward">Ward</label>
                        <select class="input" name="ward_code" id="ward_code" required="">
                            <option value="" selected="selected"> Select Ward first</option>
                        </select>
                    </div>

                    <div class="button-group">
                        <input type="reset" class="submit" value="CLEAR">
                        <input id="submit2" type="submit" value="SUBMIT"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
{#<a href={% url 'vote:photo' %}>NEXT</a>#}
{% endblock %}

templates/vote/user/logout.html
{% extends 'vote/admin/auth_base.html' %}
{% load static %}
{% block title_block %}
    <title>Logout</title>
{% endblock %}
<!DOCTYPE html>
<html lang="en">

{% block body_block %}
    <body>
        <div class="form-narrow">
            <form>
                <h1>YOU HAVE BEEN LOGGED OUT SUCCESSFULLY!</h1>
                <div class="button-container">
                    <a class="submit" href={% url 'vote:login' %}> LOGIN </a>
                    <a class="submit2" href={% url 'vote:signup' %}> SIGNUP </a>
                </div>
                <div class="options">
                    <a href="/vote" >Back to Home Page</a>
                </div>
            </form>
        </div>
    </body>
{% endblock %}